# frozen_string_literal: true

require 'rumale/svm/version'
require 'rumale/svm/svc'
require 'rumale/svm/svr'
require 'rumale/svm/nu_svc'
require 'rumale/svm/nu_svr'
require 'rumale/svm/one_class_svm'
require 'rumale/svm/linear_svc'
require 'rumale/svm/linear_svr'
require 'rumale/svm/logistic_regression'
require 'rumale/svm/linear_one_class_svm'
require 'rumale/svm/locally_linear_svc'
require 'rumale/svm/random_recursive_svc'
require 'rumale/svm/clustered_svc'
