module Rumale
  module SVM
    class LogisticRegression
      include Base::BaseEstimator
      include Base::Classifier

      attr_reader weight_vec: Numo::DFloat
      attr_reader bias_term: Numo::DFloat

      def initialize: (?penalty: String penalty, ?dual: bool dual, ?reg_param: Float reg_param,
                       ?fit_bias: bool fit_bias, ?bias_scale: Float bias_scale, ?tol: Float tol,
                       ?verbose: bool verbose, ?random_seed: untyped? random_seed) -> void
      def fit: (Numo::DFloat x, Numo::Int32 y) -> LogisticRegression
      def decision_function: (Numo::DFloat x) -> Numo::DFloat
      def predict: (Numo::DFloat x) -> Numo::Int32
      def predict_proba: (Numo::DFloat x) -> Numo::DFloat
      def marshal_dump: () -> { params: Hash[Symbol, untyped], model: untyped, weight_vec: Numo::DFloat, bias_term: Numo::DFloat }
      def marshal_load: (untyped obj) -> void

      private

      def expand_feature: (Numo::DFloat x) -> Numo::DFloat
      def weight_and_bias: (Numo::DFloat base_weight) -> [Numo::DFloat, Numo::DFloat]
      def liblinear_params: () -> untyped
      def solver_type: () -> Integer
      def binary_class?: () -> bool
      def fit_bias?: () -> bool
      def bias_scale: () -> Float
      def n_classes: () -> Integer
      def n_features: () -> Integer
      def trained?: () -> bool
    end
  end
end
